### ISSUE TITLE
Download of the Valetudo release list from Github failed!

### ISSUE THREAD

**Issue by unfassbarstephan** [LazyT/rrcc#3]
Hi,

first of all a thank you you very much for your great work.

Now to the problem:

After clicking on "Installation" in the "Valetudo" tab within the windows tool, the following message appears in German (translated into English):

"Download of the Valetudo release list from Github failed!
An error occurred during the SSL protocol."

Thank you in advance!

**Comment by lukeman11** [comment]
For me the same problem.

**Comment by LazyT** [comment]
Forgot the required dlls for SSL, will be fixt in next release.

**Comment by tl-pierre** [comment]
Hi @LazyT, I think the problem is still present in the version 0.8.1, I have this error message (appimage version on Linux Mint 19) : 
`Download Valetudo release list from Github failed! Error creating SSL context ()`

Thank you very much for this application by the way,, it has lots of great features !

**Comment by LazyT** [comment]
Ok, looks like adding libcrypto 1.0.x to the appimage solves this problem too. Guess this is the better solution... ;-)
